"""Central PostgreSQL configuration names and connection limits."""

POSTGRES_DSN_ENV_VAR = "DATA_COPILOT_POSTGRES_DSN"
POSTGRES_CONNECT_TIMEOUT_ENV_VAR = "POSTGRES_CONNECT_TIMEOUT_SECONDS"
POSTGRES_STATEMENT_TIMEOUT_ENV_VAR = "POSTGRES_STATEMENT_TIMEOUT_MS"
DEFAULT_POSTGRES_CONNECT_TIMEOUT_SECONDS = 5
DEFAULT_POSTGRES_STATEMENT_TIMEOUT_MS = 15000
MAX_POSTGRES_CONNECT_TIMEOUT_SECONDS = 60
MAX_POSTGRES_STATEMENT_TIMEOUT_MS = 120000

MAX_DATABASE_TABLES = 200
MAX_TABLE_COLUMNS = 200
MAX_RELATIONSHIPS = 200
MAX_INDEXES = 100
MAX_QUERY_ROWS = 200
MAX_QUERY_COLUMNS = 50
MAX_PLAN_NODES = 100
MAX_PLAN_DEPTH = 20
