"""Central PostgreSQL configuration names and connection limits."""

POSTGRES_DSN_ENV_VAR = "DATA_COPILOT_POSTGRES_DSN"
POSTGRES_CONNECT_TIMEOUT_ENV_VAR = "POSTGRES_CONNECT_TIMEOUT_SECONDS"
DEFAULT_POSTGRES_CONNECT_TIMEOUT_SECONDS = 5
MAX_POSTGRES_CONNECT_TIMEOUT_SECONDS = 60
