"""Small, deterministic configuration constants for the current phase."""

MAX_PROFILE_COLUMNS = 50
DEFAULT_TOP_VALUES = 10
MAX_TOP_VALUES = 20

DEFAULT_SAMPLE_ROWS = 20
MAX_SAMPLE_ROWS = 100

DEFAULT_RESULT_ROWS = 50
MAX_RESULT_ROWS = 200
MAX_RESULT_COLUMNS = 50

MAX_GROUP_BY_DIMENSIONS = 5
MAX_METRICS = 10
MAX_FILTERS = 20
