"""Deterministic Phase 3.2 semantic resolution and evidence limits."""

MAX_SEMANTIC_QUERY_TERMS = 20
MAX_SEMANTIC_EVIDENCE_DEFINITIONS = 20
MAX_SEMANTIC_TEXT_CHARS = 2000
MAX_SEMANTIC_SYNONYMS = 10
MAX_SEMANTIC_FIELDS = 20
MAX_SEMANTIC_EVIDENCE_CHARS = 12000
